// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: keleustes/renderer.proto

package keleustes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RendererType identifies which rendering backend to use.
type RendererType int32

const (
	RendererType_RENDERER_TYPE_UNSPECIFIED RendererType = 0
	RendererType_RENDERER_TYPE_PLAIN       RendererType = 1
	RendererType_RENDERER_TYPE_HELM        RendererType = 2
	RendererType_RENDERER_TYPE_KUSTOMIZE   RendererType = 3
)

// Enum value maps for RendererType.
var (
	RendererType_name = map[int32]string{
		0: "RENDERER_TYPE_UNSPECIFIED",
		1: "RENDERER_TYPE_PLAIN",
		2: "RENDERER_TYPE_HELM",
		3: "RENDERER_TYPE_KUSTOMIZE",
	}
	RendererType_value = map[string]int32{
		"RENDERER_TYPE_UNSPECIFIED": 0,
		"RENDERER_TYPE_PLAIN":       1,
		"RENDERER_TYPE_HELM":        2,
		"RENDERER_TYPE_KUSTOMIZE":   3,
	}
)

func (x RendererType) Enum() *RendererType {
	p := new(RendererType)
	*p = x
	return p
}

func (x RendererType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RendererType) Descriptor() protoreflect.EnumDescriptor {
	return file_keleustes_renderer_proto_enumTypes[0].Descriptor()
}

func (RendererType) Type() protoreflect.EnumType {
	return &file_keleustes_renderer_proto_enumTypes[0]
}

func (x RendererType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RendererType.Descriptor instead.
func (RendererType) EnumDescriptor() ([]byte, []int) {
	return file_keleustes_renderer_proto_rawDescGZIP(), []int{0}
}

// Streamed source content to be rendered.
type RenderStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderStreamRequest) Reset() {
	*x = RenderStreamRequest{}
	mi := &file_keleustes_renderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderStreamRequest) ProtoMessage() {}

func (x *RenderStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keleustes_renderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderStreamRequest.ProtoReflect.Descriptor instead.
func (*RenderStreamRequest) Descriptor() ([]byte, []int) {
	return file_keleustes_renderer_proto_rawDescGZIP(), []int{0}
}

func (x *RenderStreamRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Rendered Kubernetes manifests.
type RenderStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderStreamResponse) Reset() {
	*x = RenderStreamResponse{}
	mi := &file_keleustes_renderer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderStreamResponse) ProtoMessage() {}

func (x *RenderStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keleustes_renderer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderStreamResponse.ProtoReflect.Descriptor instead.
func (*RenderStreamResponse) Descriptor() ([]byte, []int) {
	return file_keleustes_renderer_proto_rawDescGZIP(), []int{1}
}

func (x *RenderStreamResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Streamed source content to be rendered.
type RenderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	mi := &file_keleustes_renderer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keleustes_renderer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_keleustes_renderer_proto_rawDescGZIP(), []int{2}
}

func (x *RenderRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Rendered Kubernetes manifests.
type RenderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderResponse) Reset() {
	*x = RenderResponse{}
	mi := &file_keleustes_renderer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderResponse) ProtoMessage() {}

func (x *RenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keleustes_renderer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderResponse.ProtoReflect.Descriptor instead.
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return file_keleustes_renderer_proto_rawDescGZIP(), []int{3}
}

var File_keleustes_renderer_proto protoreflect.FileDescriptor

const file_keleustes_renderer_proto_rawDesc = "" +
	"\n" +
	"\x18keleustes/renderer.proto\x12\tkeleustes\")\n" +
	"\x13RenderStreamRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"*\n" +
	"\x14RenderStreamResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"#\n" +
	"\rRenderRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x10\n" +
	"\x0eRenderResponse*{\n" +
	"\fRendererType\x12\x1d\n" +
	"\x19RENDERER_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RENDERER_TYPE_PLAIN\x10\x01\x12\x16\n" +
	"\x12RENDERER_TYPE_HELM\x10\x02\x12\x1b\n" +
	"\x17RENDERER_TYPE_KUSTOMIZE\x10\x032\xa7\x01\n" +
	"\x0fRendererService\x12S\n" +
	"\fRenderStream\x12\x1e.keleustes.RenderStreamRequest\x1a\x1f.keleustes.RenderStreamResponse(\x010\x01\x12?\n" +
	"\x06Render\x12\x18.keleustes.RenderRequest\x1a\x19.keleustes.RenderResponse(\x01B!Z\x1fgithub.com/katastroma/keleustesb\x06proto3"

var (
	file_keleustes_renderer_proto_rawDescOnce sync.Once
	file_keleustes_renderer_proto_rawDescData []byte
)

func file_keleustes_renderer_proto_rawDescGZIP() []byte {
	file_keleustes_renderer_proto_rawDescOnce.Do(func() {
		file_keleustes_renderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keleustes_renderer_proto_rawDesc), len(file_keleustes_renderer_proto_rawDesc)))
	})
	return file_keleustes_renderer_proto_rawDescData
}

var file_keleustes_renderer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keleustes_renderer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_keleustes_renderer_proto_goTypes = []any{
	(RendererType)(0),            // 0: keleustes.RendererType
	(*RenderStreamRequest)(nil),  // 1: keleustes.RenderStreamRequest
	(*RenderStreamResponse)(nil), // 2: keleustes.RenderStreamResponse
	(*RenderRequest)(nil),        // 3: keleustes.RenderRequest
	(*RenderResponse)(nil),       // 4: keleustes.RenderResponse
}
var file_keleustes_renderer_proto_depIdxs = []int32{
	1, // 0: keleustes.RendererService.RenderStream:input_type -> keleustes.RenderStreamRequest
	3, // 1: keleustes.RendererService.Render:input_type -> keleustes.RenderRequest
	2, // 2: keleustes.RendererService.RenderStream:output_type -> keleustes.RenderStreamResponse
	4, // 3: keleustes.RendererService.Render:output_type -> keleustes.RenderResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keleustes_renderer_proto_init() }
func file_keleustes_renderer_proto_init() {
	if File_keleustes_renderer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keleustes_renderer_proto_rawDesc), len(file_keleustes_renderer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keleustes_renderer_proto_goTypes,
		DependencyIndexes: file_keleustes_renderer_proto_depIdxs,
		EnumInfos:         file_keleustes_renderer_proto_enumTypes,
		MessageInfos:      file_keleustes_renderer_proto_msgTypes,
	}.Build()
	File_keleustes_renderer_proto = out.File
	file_keleustes_renderer_proto_goTypes = nil
	file_keleustes_renderer_proto_depIdxs = nil
}
