// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: keleustes/renderer.proto

package keleustes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Streamed source content to be rendered.
type RenderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	mi := &file_keleustes_renderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keleustes_renderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_keleustes_renderer_proto_rawDescGZIP(), []int{0}
}

func (x *RenderRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Rendered Kubernetes manifests.
type RenderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifests     [][]byte               `protobuf:"bytes,1,rep,name=manifests,proto3" json:"manifests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderResponse) Reset() {
	*x = RenderResponse{}
	mi := &file_keleustes_renderer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderResponse) ProtoMessage() {}

func (x *RenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keleustes_renderer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderResponse.ProtoReflect.Descriptor instead.
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return file_keleustes_renderer_proto_rawDescGZIP(), []int{1}
}

func (x *RenderResponse) GetManifests() [][]byte {
	if x != nil {
		return x.Manifests
	}
	return nil
}

var File_keleustes_renderer_proto protoreflect.FileDescriptor

const file_keleustes_renderer_proto_rawDesc = "" +
	"\n" +
	"\x18keleustes/renderer.proto\x12\tkeleustes\"#\n" +
	"\rRenderRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\".\n" +
	"\x0eRenderResponse\x12\x1c\n" +
	"\tmanifests\x18\x01 \x03(\fR\tmanifests2R\n" +
	"\x0fRendererService\x12?\n" +
	"\x06Render\x12\x18.keleustes.RenderRequest\x1a\x19.keleustes.RenderResponse(\x01B!Z\x1fgithub.com/katastroma/keleustesb\x06proto3"

var (
	file_keleustes_renderer_proto_rawDescOnce sync.Once
	file_keleustes_renderer_proto_rawDescData []byte
)

func file_keleustes_renderer_proto_rawDescGZIP() []byte {
	file_keleustes_renderer_proto_rawDescOnce.Do(func() {
		file_keleustes_renderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keleustes_renderer_proto_rawDesc), len(file_keleustes_renderer_proto_rawDesc)))
	})
	return file_keleustes_renderer_proto_rawDescData
}

var file_keleustes_renderer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_keleustes_renderer_proto_goTypes = []any{
	(*RenderRequest)(nil),  // 0: keleustes.RenderRequest
	(*RenderResponse)(nil), // 1: keleustes.RenderResponse
}
var file_keleustes_renderer_proto_depIdxs = []int32{
	0, // 0: keleustes.RendererService.Render:input_type -> keleustes.RenderRequest
	1, // 1: keleustes.RendererService.Render:output_type -> keleustes.RenderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keleustes_renderer_proto_init() }
func file_keleustes_renderer_proto_init() {
	if File_keleustes_renderer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keleustes_renderer_proto_rawDesc), len(file_keleustes_renderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keleustes_renderer_proto_goTypes,
		DependencyIndexes: file_keleustes_renderer_proto_depIdxs,
		MessageInfos:      file_keleustes_renderer_proto_msgTypes,
	}.Build()
	File_keleustes_renderer_proto = out.File
	file_keleustes_renderer_proto_goTypes = nil
	file_keleustes_renderer_proto_depIdxs = nil
}
