// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: keleustes/renderer.proto

package keleustes

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RendererService_Render_FullMethodName = "/keleustes.RendererService/Render"
)

// RendererServiceClient is the client API for RendererService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RendererService produces Kubernetes manifests from source content.
type RendererServiceClient interface {
	Render(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RenderRequest, RenderResponse], error)
}

type rendererServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRendererServiceClient(cc grpc.ClientConnInterface) RendererServiceClient {
	return &rendererServiceClient{cc}
}

func (c *rendererServiceClient) Render(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RenderRequest, RenderResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RendererService_ServiceDesc.Streams[0], RendererService_Render_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RenderRequest, RenderResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RendererService_RenderClient = grpc.ClientStreamingClient[RenderRequest, RenderResponse]

// RendererServiceServer is the server API for RendererService service.
// All implementations must embed UnimplementedRendererServiceServer
// for forward compatibility.
//
// RendererService produces Kubernetes manifests from source content.
type RendererServiceServer interface {
	Render(grpc.ClientStreamingServer[RenderRequest, RenderResponse]) error
	mustEmbedUnimplementedRendererServiceServer()
}

// UnimplementedRendererServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRendererServiceServer struct{}

func (UnimplementedRendererServiceServer) Render(grpc.ClientStreamingServer[RenderRequest, RenderResponse]) error {
	return status.Error(codes.Unimplemented, "method Render not implemented")
}
func (UnimplementedRendererServiceServer) mustEmbedUnimplementedRendererServiceServer() {}
func (UnimplementedRendererServiceServer) testEmbeddedByValue()                         {}

// UnsafeRendererServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RendererServiceServer will
// result in compilation errors.
type UnsafeRendererServiceServer interface {
	mustEmbedUnimplementedRendererServiceServer()
}

func RegisterRendererServiceServer(s grpc.ServiceRegistrar, srv RendererServiceServer) {
	// If the following call panics, it indicates UnimplementedRendererServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RendererService_ServiceDesc, srv)
}

func _RendererService_Render_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RendererServiceServer).Render(&grpc.GenericServerStream[RenderRequest, RenderResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RendererService_RenderServer = grpc.ClientStreamingServer[RenderRequest, RenderResponse]

// RendererService_ServiceDesc is the grpc.ServiceDesc for RendererService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RendererService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keleustes.RendererService",
	HandlerType: (*RendererServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Render",
			Handler:       _RendererService_Render_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "keleustes/renderer.proto",
}
